### ISSUE TITLE
Transponder.TV doesn't launch on Kodi 18 (UWP)

### ISSUE THREAD

**Issue by 24mu13** [Lunatixz/KODI_Addons#35]
Just tried Transponder.TV on brand-new Kodi 18 (using Windows 10 UWP), and got this error:
```
15:01:23.337 T:23152   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named _winreg
                                            Traceback (most recent call last):
                                              File "C:\Users\XX\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\plugin.video.transpondertv\default.py", line 23, in <module>
                                                from resources.lib import transponder
                                              File "C:\Users\XX\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\plugin.video.transpondertv\resources\lib\transponder.py", line 21, in <module>
                                                import urlparse, urllib, urllib2, socket, json, requests, mechanize, cookielib
                                              File "C:\Users\XX\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\script.module.mechanize\lib\mechanize\__init__.py", line 164, in <module>
                                                from _msiecookiejar import MSIECookieJar
                                              File "C:\Users\XX\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\script.module.mechanize\lib\mechanize\_msiecookiejar.py", line 16, in <module>
                                                import _winreg
                                            ImportError: No module named _winreg
                                            -->End of Python script error report<--
15:01:23.356 T:23632   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.transpondertv/
15:01:23.365 T:25788   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.transpondertv/) failed
```

**Comment by Lunatixz** [comment]
Thanks, I'll look into the issue...

**Comment by 24mu13** [comment]
Still not working right now, but I just realised the problem is Transponder.TV not free anymore for majority of their channels. If you have a paid plan will work most probably: I tried **Drama TV** for instance.
