### ISSUE TITLE
[Disclose.TV] cant play anything

### ISSUE THREAD

**Issue by kekukui** [Lunatixz/KODI_Addons#46]
```
ERROR: plugin.video.disclosetv-1.0.8-resolveURL Failed! 'dtv_video' ,Traceback (most recent call last):
File "/storage/.kodi/addons/plugin.video.disclosetv/resources/lib/disclosetv.py", line 126, in resolveURL
data = json.loads(re.findall('"drupal-settings-json">(.+?)</script>',self.openURL(url), flags=re.DOTALL)[0])['dtv_video']
KeyError: 'dtv_video'
script.module.youtube.dl: youtube_dl core version: 2018.11.07
WARNING: addons must not activate DialogBusy

Error Contents: Unknown exception thrown from the call "XBMCAddon::xbmcplugin::setResolvedUrl"
Traceback (most recent call last):
File "/storage/.kodi/addons/plugin.video.disclosetv/default.py", line 24, in <module>
if __name__ == '__main__': disclosetv.Disclose(sys.argv).run()
File "/storage/.kodi/addons/plugin.video.disclosetv/resources/lib/disclosetv.py", line 216, in run
elif mode == 9: self.playVideo(name, url)
File "/storage/.kodi/addons/plugin.video.disclosetv/resources/lib/disclosetv.py", line 161, in playVideo
xbmcplugin.setResolvedUrl(int(self.sysARG[1]), True, self.resolveURL(name, url))
RuntimeError: Unknown exception thrown from the call "XBMCAddon::xbmcplugin::setResolvedUrl"
-->End of Python script error report<--
```

**Comment by Lunatixz** [comment]
Website changed plug-in is broken until I update, THX
