### ISSUE TITLE
[ModuleAuditor] handling connection errors

### ISSUE THREAD

**Issue by kekukui** [Lunatixz/KODI_Addons#47]
During an internet outage, the Kodi user interface froze around the time the following errors occurred

```
ERROR: service.moduleauditor-0.1.4-openURL Failed! <urlopen error [Errno 111] Connection refused>
Traceback (most recent call last):
File "/storage/.kodi/addons/service.moduleauditor/scan.py", line 206, in openURL
  page = urllib2.urlopen(req, timeout=TIMEOUT)
 File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
 File "/usr/lib/python2.7/urllib2.py", line 429, in open
 File "/usr/lib/python2.7/urllib2.py", line 447, in _open
 File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
 File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
 File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
URLError: <urlopen error [Errno 111] Connection refused>
```

```
ERROR: service.moduleauditor-0.1.4-buildModules, Failed! no element found: line 1, column 0
Traceback (most recent call last):
 File "/storage/.kodi/addons/service.moduleauditor/scan.py", line 347, in buildModules
 tree = ET.fromstring(self.openURL(BASE_URL%(branch)))
 File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1312, in XML
 File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1671, in close
 File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
ParseError: no element found: line 1, column 0
```

**Comment by Lunatixz** [comment]
Thanks however it's unlikely Kodi froze from these errors as they already have error handling and I do not call any window models so the script does not have the ability to do disable user input.

Those errors were generated from the internet failure... The lockup could have come from a number of sources. If you provide a full log I can debug. THX

**Comment by Lunatixz** [comment]
v.0.1.5
