### ISSUE TITLE
[NewsOn] cannot play newscasts

### ISSUE THREAD

**Issue by kekukui** [Lunatixz/KODI_Addons#65]
```
ERROR: NEWADDON Unknown Video Info Key "label"
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!

Error Type: <type 'exceptions.TypeError'>
Error Contents: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):

File "/storage/.kodi/addons/plugin.video.newson/default.py", line 24, in <module>
 if __name__ == '__main__': newson.NewsOn(sys.argv).run()

File "/storage/.kodi/addons/plugin.video.newson/resources/lib/newson.py", line 251, in run
 elif mode == 1: self.newsCasts(url)

File "/storage/.kodi/addons/plugin.video.newson/resources/lib/newson.py", line 145, in newsCasts
 chid = chid+'.%d'%idx if idx > 0 else chid

TypeError: unsupported operand type(s) for +: 'int' and 'str'
 -->End of Python script error report<--
```

**Comment by Lunatixz** [comment]
Submitted to Kodis repo v.19

**Comment by kekukui** [comment]
I see all that stuff getting patched up for Matrix compatibility - thanks mate 👍🏽 👍🏽 👍🏽
